# Generated by Django 3.2.11 on 2022-01-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name of product')),
                ('category', models.IntegerField(default=5, verbose_name='Category')),
                ('unit', models.CharField(max_length=20, verbose_name='Unit')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('price_selling', models.FloatField(default=0, verbose_name='Price selling')),
                ('price_on_sale', models.FloatField(default=0, verbose_name='Price on sale')),
                ('number_prod_sold', models.IntegerField(default=0, verbose_name='Number of product sold')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('sale', models.BooleanField(default=False, verbose_name='Sale')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('owner', models.CharField(max_length=20, verbose_name='Name of owner')),
                ('quantity_in_stock', models.IntegerField(default=50, verbose_name='Stock quantity')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_date', models.DateTimeField(verbose_name='Date de transaction')),
                ('selling_quantity', models.IntegerField(default=0, verbose_name='Quantite de retrait')),
                ('amount_total', models.FloatField(verbose_name='Sum of money')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ('selling_date',),
            },
        ),
        migrations.CreateModel(
            name='ImportStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(verbose_name='Date import')),
                ('import_quantity', models.IntegerField(default=0, verbose_name='Quantite de Import')),
                ('amount_spending', models.FloatField(verbose_name='Sum of spending')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ('import_date',),
            },
        ),
    ]
